// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEWWEmntLEDFqy4taCyObSj-fiFQuzX74',
    appId: '1:281097569077:web:e15118a28e149aa03cc27c',
    messagingSenderId: '281097569077',
    projectId: 'mobi-12',
    authDomain: 'mobi-12.firebaseapp.com',
    storageBucket: 'mobi-12.appspot.com',
    measurementId: 'G-HG6NHJZLGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH_4DReyj9z6e2TYpZo9S0E9JdjQwaQo8',
    appId: '1:281097569077:android:f579fa164017b8733cc27c',
    messagingSenderId: '281097569077',
    projectId: 'mobi-12',
    storageBucket: 'mobi-12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkQIN73ystR5rncY_Vn7jCXd1ueYaSctw',
    appId: '1:281097569077:ios:36679d4b7bb56ce83cc27c',
    messagingSenderId: '281097569077',
    projectId: 'mobi-12',
    storageBucket: 'mobi-12.appspot.com',
    iosBundleId: 'com.example.monitoringapplicatie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkQIN73ystR5rncY_Vn7jCXd1ueYaSctw',
    appId: '1:281097569077:ios:36679d4b7bb56ce83cc27c',
    messagingSenderId: '281097569077',
    projectId: 'mobi-12',
    storageBucket: 'mobi-12.appspot.com',
    iosBundleId: 'com.example.monitoringapplicatie',
  );
}
