var DATA = [
      { id:0, label:"com.xsens.dot.android.sdk", link:"com/xsens/dot/android/sdk/package-summary.html", type:"package" },
      { id:1, label:"com.xsens.dot.android.sdk.DotSdk", link:"com/xsens/dot/android/sdk/DotSdk.html", type:"class" },
      { id:2, label:"com.xsens.dot.android.sdk.events", link:"com/xsens/dot/android/sdk/events/package-summary.html", type:"package" },
      { id:3, label:"com.xsens.dot.android.sdk.events.DotData", link:"com/xsens/dot/android/sdk/events/DotData.html", type:"class" },
      { id:4, label:"com.xsens.dot.android.sdk.interfaces", link:"com/xsens/dot/android/sdk/interfaces/package-summary.html", type:"package" },
      { id:5, label:"com.xsens.dot.android.sdk.interfaces.DotCiCallback", link:"com/xsens/dot/android/sdk/interfaces/DotCiCallback.html", type:"class" },
      { id:6, label:"com.xsens.dot.android.sdk.interfaces.DotDeviceCallback", link:"com/xsens/dot/android/sdk/interfaces/DotDeviceCallback.html", type:"class" },
      { id:7, label:"com.xsens.dot.android.sdk.interfaces.DotMeasurementCallback", link:"com/xsens/dot/android/sdk/interfaces/DotMeasurementCallback.html", type:"class" },
      { id:8, label:"com.xsens.dot.android.sdk.interfaces.DotRecordingCallback", link:"com/xsens/dot/android/sdk/interfaces/DotRecordingCallback.html", type:"class" },
      { id:9, label:"com.xsens.dot.android.sdk.interfaces.DotScannerCallback", link:"com/xsens/dot/android/sdk/interfaces/DotScannerCallback.html", type:"class" },
      { id:10, label:"com.xsens.dot.android.sdk.interfaces.DotSyncCallback", link:"com/xsens/dot/android/sdk/interfaces/DotSyncCallback.html", type:"class" },
      { id:11, label:"com.xsens.dot.android.sdk.interfaces.SettingsCallback", link:"com/xsens/dot/android/sdk/interfaces/SettingsCallback.html", type:"class" },
      { id:12, label:"com.xsens.dot.android.sdk.models", link:"com/xsens/dot/android/sdk/models/package-summary.html", type:"package" },
      { id:13, label:"com.xsens.dot.android.sdk.models.DotDevice", link:"com/xsens/dot/android/sdk/models/DotDevice.html", type:"class" },
      { id:14, label:"com.xsens.dot.android.sdk.models.DotPayload", link:"com/xsens/dot/android/sdk/models/DotPayload.html", type:"class" },
      { id:15, label:"com.xsens.dot.android.sdk.models.DotProductId", link:"com/xsens/dot/android/sdk/models/DotProductId.html", type:"class" },
      { id:16, label:"com.xsens.dot.android.sdk.models.DotRecordingFileInfo", link:"com/xsens/dot/android/sdk/models/DotRecordingFileInfo.html", type:"class" },
      { id:17, label:"com.xsens.dot.android.sdk.models.DotRecordingState", link:"com/xsens/dot/android/sdk/models/DotRecordingState.html", type:"class" },
      { id:18, label:"com.xsens.dot.android.sdk.models.DotResetData", link:"com/xsens/dot/android/sdk/models/DotResetData.html", type:"class" },
      { id:19, label:"com.xsens.dot.android.sdk.models.DotSyncManager", link:"com/xsens/dot/android/sdk/models/DotSyncManager.html", type:"class" },
      { id:20, label:"com.xsens.dot.android.sdk.models.FilterProfileInfo", link:"com/xsens/dot/android/sdk/models/FilterProfileInfo.html", type:"class" },
      { id:21, label:"com.xsens.dot.android.sdk.models.FilterProfileInfo.PropertyType", link:"com/xsens/dot/android/sdk/models/FilterProfileInfo.PropertyType.html", type:"class" },
      { id:22, label:"com.xsens.dot.android.sdk.models.VersionModel", link:"com/xsens/dot/android/sdk/models/VersionModel.html", type:"class" },
      { id:23, label:"com.xsens.dot.android.sdk.recording", link:"com/xsens/dot/android/sdk/recording/package-summary.html", type:"package" },
      { id:24, label:"com.xsens.dot.android.sdk.recording.DotRecordingManager", link:"com/xsens/dot/android/sdk/recording/DotRecordingManager.html", type:"class" },
      { id:25, label:"com.xsens.dot.android.sdk.settings", link:"com/xsens/dot/android/sdk/settings/package-summary.html", type:"package" },
      { id:26, label:"com.xsens.dot.android.sdk.settings.DotResetResults", link:"com/xsens/dot/android/sdk/settings/DotResetResults.html", type:"class" },
      { id:27, label:"com.xsens.dot.android.sdk.settings.DotSettingsManager", link:"com/xsens/dot/android/sdk/settings/DotSettingsManager.html", type:"class" },
      { id:28, label:"com.xsens.dot.android.sdk.utils", link:"com/xsens/dot/android/sdk/utils/package-summary.html", type:"package" },
      { id:29, label:"com.xsens.dot.android.sdk.utils.DotCompatibleUtil", link:"com/xsens/dot/android/sdk/utils/DotCompatibleUtil.html", type:"class" },
      { id:30, label:"com.xsens.dot.android.sdk.utils.DotDebugger", link:"com/xsens/dot/android/sdk/utils/DotDebugger.html", type:"class" },
      { id:31, label:"com.xsens.dot.android.sdk.utils.DotLogger", link:"com/xsens/dot/android/sdk/utils/DotLogger.html", type:"class" },
      { id:32, label:"com.xsens.dot.android.sdk.utils.DotParser", link:"com/xsens/dot/android/sdk/utils/DotParser.html", type:"class" },
      { id:33, label:"com.xsens.dot.android.sdk.utils.DotScanner", link:"com/xsens/dot/android/sdk/utils/DotScanner.html", type:"class" }

    ];
